name: Deploy Angular App to S3 Bucket and CloudFront

on:
  push:
    branches:
      - angular-application  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build 

    - name: List the dir 
      run: |
        ls -ltr
        cd dist
        ls -ltr

    # - name: Deploy to S3 bucket
    #   uses: jakejarvis/s3-sync-action@v0.4.0
    #   with:
    #     args: --acl public-read --delete
    #   env:
    #     AWS_S3_BUCKET: "dgeetkar-test-bucket"  # Your S3 bucket name
    #     AWS_REGION: "ap-southeast-1"  # Your AWS region
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     SOURCE_DIR: "./dist/machinetest"  # Specify the exact folder to upload from the dist directory

    # Sync the build folder to S3
    - name: Deploy to S3
      run: |
        aws s3 sync ./dist/machinetest/ s3://dgeetkar-test-bucket/ --delete --acl public-read


    - name: Create CloudFront invalidation
      run: aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
